apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-ui.fullname" . }}
  labels:
{{ include "guestbook-ui.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "guestbook-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
