{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "guestbook-ui.serviceAccountName" . }}
  labels:
{{ include "guestbook-ui.labels" . | indent 4 }}
{{- end -}}
